### ISSUE TITLE
Tests not hitting APP_URL in proxy environment

### ISSUE THREAD

**Issue by haakym** [Modelizer/Selenium#15] opened 2016-09-29 14:19 UTC
Hi. Firstly, great idea for a package I look forward to seeing it develop further!

I'm developing locally using Laragon on Windows 7 for which I used to start up a fresh install of Laravel 5.3 and pulled in the package and then followed the installation instructions from the readme.

I've added the following values to my `.env` file:

APP_URL="http://modelizer-selenium.dev/"
SELENIUM_WIDTH=1024
SELENIUM_HEIGHT=768

Then when I run the selenium server and phpunit it hits localhost and not http://modelizer-selenium.dev/, this is what I've got in the console which is the Laragon splash page which is returned when you hit localhost:

```
C:\laragon\www\modelizer-selenium (master) 29/09/2016 14:57:15.43                                                                     
λ phpunit                                                                                                                             
PHPUnit 5.5.5 by Sebastian Bergmann and contributors.                                                                                 

.E                                                                  2 / 2 (100%)                                                      

Time: 318 ms, Memory: 8.00MB                                                                                                          

There was 1 error:                                                                                                                    

1) SeleniumExampleTest::testBasicExample                                                                                              
PHPUnit_Extensions_Selenium2TestCase_Exception: JSON decoding of remote response failed.                                              
Error code: 4                                                                                                                         
The response: '<!DOCTYPE html>                                                                                                        
<html>                                                                                                                                
    <head>                                                                                                                            
        <title>Laragon</title                                                                                                        
    </head>                                                                                                                           
    <body>                                                                                                                            
        <div class="container">                                                                                                       
            <div class="content">                                                                                                     
                <div class="title" title="Laragon">Laragon</div>                                                                      

                <div class="info"><br />                                                                                              
                      Apache/2.4.23 (Win32) mod_authnz_sspi/0.1.0 OpenSSL/1.0.2h PHP/7.0.10<br />                                     
                      PHP version: 7.0.10   <span><a title="phpinfo()" href="/?q=info">info</a></span><br />                          
                      Document Root: C:/laragon/www<br />                                                                             

                </div>                                                                                                                
                <div class="opt">                                                                                                     
                  <div><a title="Getting Started" href="http://laragon.org/?q=getting-started">Getting Started</a></div>              
                </div>                                                                                                                
            </div>                                                                                                                    

        </div>                                                                                                                        
    </body>                                                                                                                           
</html>'                                                                                                                              


C:\laragon\www\modelizer-selenium\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase\Driver.php:142                 
C:\laragon\www\modelizer-selenium\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase\Driver.php:71                  
C:\laragon\www\modelizer-selenium\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase\SessionStrategy\Isolated.php:67
C:\laragon\www\modelizer-selenium\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase.php:296                        
C:\laragon\www\modelizer-selenium\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase.php:337                        
C:\laragon\www\modelizer-selenium\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase.php:314                        
C:\Users\djones.SACBUK\AppData\Roaming\Composer\vendor\phpunit\phpunit\src\TextUI\Command.php:162                                     
C:\Users\djones.SACBUK\AppData\Roaming\Composer\vendor\phpunit\phpunit\src\TextUI\Command.php:113                                     

ERRORS!                                                                                                                               
Tests: 2, Assertions: 2, Errors: 1.                                                                                                   
```

I also tried adding the following to my phpunit.xml:

```
<env name="APP_URL" value="http://modelizer-selenium.dev/"/>
```

this to my tests/TestCase.php:

```
protected $baseUrl = 'http://modelizer-selenium.dev';
```

The failing test looks like this:

```
    public function testBasicExample()
    {
        // This is a sample code you can change as per your current scenario
        $this->visit('/')
             ->see('Laravel')
             ->hold(3);
    }
```

Any ideas? Thanks!

**Comment by haakym** [comment] 2016-09-29 14:35
Related? 

https://github.com/Codeception/Codeception/issues/2651

If this is an issue with proxy settings, how or where can I set them?

**Comment by Modelizer** [comment] 2016-09-30 09:32
Thanks a lot @haakym 
If this is in your test case

```
$this->visit('/')
             ->see('Laravel')
             ->hold(3);
```

Then test will fail because it's looking for `Laravel` and your body contain `Laragon`

Also, it seems the problem is not related to baseUrl because phpunit is not able to decode json `PHPUnit_Extensions_Selenium2TestCase_Exception: JSON decoding of remote response failed.`

Also, your tag at `<title>Laragon</title` is not been close properly.

**Comment by haakym** [comment] 2016-09-30 10:11
@Modelizer 

Thanks for your reply! I'm not sure you fully understood my issue, I will try to explain in more detail.

The test fails because it's hitting the wrong URL which gives different content to what is expected. I'm using a WAMP app called Laragon and that's the splash page which is shown at `http://localhost`.

I thought the issue was related to the baseUrl because it was going to `http://localhost` instead of my desired URL: `http://modelizer-selenium.dev`

After googling some of the output after running `phpunit` I now believe the issue is related to the chrome webdriver and proxy settings (I'm behind a proxy at my work place), as others were having issues using codeception and the chrome webdriver here: https://github.com/Codeception/Codeception/issues/3042 and here https://github.com/Codeception/Codeception/issues/2651

How would I be able to set the proxy settings to resolve this issue?

**Comment by Modelizer** [comment] 2016-09-30 14:19
Okay.

What if we provide an option which will be loaded when selenium server is started.
Example `PHP artisan selenium:start --proxy-server=192.168.1.1`

Will this help you?
Because right now I think we need to tell selenium which proxy needs to be loaded, check [this](http://stackoverflow.com/questions/19225507/how-to-set-proxy-setting-for-chrome-in-selenium-java) out.

This issue is new for me correct me if I'm wrong :)

**Comment by haakym** [comment] 2016-10-06 10:43
@Modelizer 

Sorry for the late reply.

> What if we provide an option which will be loaded when selenium server is started.
> Example PHP artisan selenium:start --proxy-server=192.168.1.1
> 
> Will this help you?

Yes, that looks good! To be honest, it's new for me too.

**Comment by Modelizer** [comment] 2016-11-16 09:52
Now you can try https://github.com/Modelizer/Selenium/wiki/Selenium-Options#proxyinjectionmode

**Comment by haakym** [comment] 2016-11-16 10:21
@Modelizer - awesome, I'll give this a try soon and will be sure to give feedback

**Comment by Modelizer** [comment] 2016-11-21 10:48
closing this issue for now.

**Comment by haakym** [comment] 2016-11-22 10:31
@Modelizer I've done the following...

1. `laravel new seleniumtest`

now if I go to `http://seleniumtest.dev/` I see the following in my browser:

![image](https://cloud.githubusercontent.com/assets/832687/20520403/96782698-b09e-11e6-8880-841729047323.png)


2. `composer require modelizer/selenium "~1.0"`

3. add to .env:
```
APP_URL="http://seleniumtest.dev/"
SELENIUM_WIDTH=1024
SELENIUM_HEIGHT=768
```

4. add to app.php
```php
Modelizer\Selenium\SeleniumServiceProvider::class,
```

5. `php artisan selenium:make:test SeleniumExampleTest`

6. add to SeleniumExampleTest.php:
```php
    public function testBasicExample()
    {
        // This is a sample code you can change as per your current scenario
        $this->visit('/')
             ->see('Laravel')
             ->hold(3);
    }
```

7. create file: `config/selenium.php` with following content:
```php
<?php

return [
	'proxyInjectionMode' => true
];
```

Unsure I am doing the correct thing here?

8. `php artisan selenium:start`

When running `phpunit` I get the same issue as before:
 - the tests appear to be hitting the server software splash page on `http://localhost` not `http://seleniumtest.dev`

```
PHPUnit 5.6.5 by Sebastian Bergmann and contributors.                                                                           
                                                                                                                                
.E                                                                  2 / 2 (100%)                                                
                                                                                                                                
Time: 234 ms, Memory: 10.00MB                                                                                                   
                                                                                                                                
There was 1 error:                                                                                                              
                                                                                                                                
1) SeleniumExampleTest::testBasicExample                                                                                        
PHPUnit_Extensions_Selenium2TestCase_Exception: JSON decoding of remote response failed.                                        
Error code: 4                                                                                                                   
The response: '<!DOCTYPE html>                                                                                                  
<html>                                                                                                                          
    <head>                                                                                                                      
        <title>Laragon</title>                                                                                                  
                                                                                                                                
        <link href="https://fonts.googleapis.com/css?family=Karla:400" rel="stylesheet" type="text/css">                        
                                                                                                                                
        <style>                                                                                                                 
            html, body {                                                                                                        
                height: 100%;                                                                                                   
            }                                                                                                                   
                                                                                                                                
            body {                                                                                                              
                margin: 0;                                                                                                      
                padding: 0;                                                                                                     
                width: 100%;                                                                                                    
                display: table;                                                                                                 
                font-weight: 100;                                                                                               
                font-family: 'Karla';                                                                                           
            }                                                                                                                   
                                                                                                                                
            .container {                                                                                                        
                text-align: center;                                                                                             
                display: table-cell;                                                                                            
                vertical-align: middle;                                                                                         
            }                                                                                                                   
                                                                                                                                
            .content {                                                                                                          
                text-align: center;                                                                                             
                display: inline-block;                                                                                          
            }                                                                                                                   
                                                                                                                                
            .title {                                                                                                            
                font-size: 96px;                                                                                                
            }                                                                                                                   
                                                                                                                                
            .opt {                                                                                                              
                margin-top: 30px;                                                                                               
            }                                                                                                                   
                                                                                                                                
            .opt a {                                                                                                            
              text-decoration: none;                                                                                            
              font-size: 150%;                                                                                                  
            }                                                                                                                   
                                                                                                                                
            a:hover {                                                                                                           
              color: red;                                                                                                       
            }                                                                                                                   
        </style>                                                                                                                
    </head>                                                                                                                     
    <body>                                                                                                                      
        <div class="container">                                                                                                 
            <div class="content">                                                                                               
                <div class="title" title="Laragon">Laragon</div>                                                                
                                                                                                                                
                <div class="info"><br />                                                                                        
                      Apache/2.4.23 (Win32) mod_authnz_sspi/0.1.0 OpenSSL/1.0.2h PHP/7.0.10<br />                               
                      PHP version: 7.0.10   <span><a title="phpinfo()" href="/?q=info">info</a></span><br />                    
                      Document Root: C:/laragon/www<br />                                                                       
                                                                                                                                
                </div>                                                                                                          
                <div class="opt">                                                                                               
                  <div><a title="Getting Started" href="http://laragon.org/?q=getting-started">Getting Started</a></div>        
                </div>                                                                                                          
            </div>                                                                                                              
                                                                                                                                
        </div>                                                                                                                  
    </body>                                                                                                                     
</html>'                                                                                                                        
                                                                                                                                
                                                                                                                                
C:\laragon\www\seleniumtest\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase\Driver.php:142                 
C:\laragon\www\seleniumtest\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase\Driver.php:71                  
C:\laragon\www\seleniumtest\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase\SessionStrategy\Isolated.php:67
C:\laragon\www\seleniumtest\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase.php:296                        
C:\laragon\www\seleniumtest\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase.php:337                        
C:\laragon\www\seleniumtest\vendor\phpunit\phpunit-selenium\PHPUnit\Extensions\Selenium2TestCase.php:314                        
                                                                                                                                
ERRORS!                                                                                                                         
Tests: 2, Assertions: 2, Errors: 1.                                                                                             
```

Any suggestions would be appreciated. Thank you very much!

**Comment by Modelizer** [comment] 2016-11-22 11:24
ping @jhoopes @chrispecoraro Have you guys have any idea what is going on? :thinking: 

I think if we able to pass a correct `APP_URL` in the proxy environment will solve this issue.

**Comment by haakym** [comment] 2016-11-22 12:36
Just to add some further context if you didn't read my first few posts on this issue, I am using this package at work where we're behind a proxy and thought this was causing the issue as googling similar errors brought up results related to proxy settings for selenium?

**Comment by paulg446** [comment] 2016-12-05 19:28
@haakym try removing the trailing forward slash from the APP_URL... APP_URL="http://seleniumtest.dev/" => APP_URL="http://seleniumtest.dev"
And then with testing, omit first forward slash also, ie  $this->visit('foo') instead of  $this->visit('/foo')

**Comment by Modelizer** [comment] 2018-04-07 23:33
Upgrading to 2.0 should solve this problem.

**Closed as completed by Modelizer** 2018-04-07 23:33 UTC
Labels: bug, hacktoberfest
