### ISSUE TITLE
ERROR: Exception in thread "main" java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by tyler36** [Modelizer/Selenium#25] opened 2016-12-02 04:02 UTC
Hi,

Recently, I got this error on a new project when trying to run "php artisan selenium:start":
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/openqa/grid/selenium/GridLauncher : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$000(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: org.openqa.grid.selenium.GridLauncher. Program will exit.
```

It was working on my other project. After some debugging, I realized it was a PHP issue.
My new project required PHP v5.6 (my other project v7.0).
"php artisan selenium:start" always fails when my system is set to PHP 5.6, but passes on PHP 7.0.
I didn't see anything on the site stating a minimum PHP version so perhaps this might be required?

OS: Win10
PHP: 5.6 / 7.0
Modelizer/Selenium: 1.1

**Comment by Modelizer** [comment] 2016-12-02 07:08
I tested it on `PHP 5.6.28` and its working fine. Can you please debug it more or provide more information to reproduce it.

**Comment by tyler36** [comment] 2016-12-02 07:10
I'm on ```PHP 5.6.18``` ... I'll try and do some more debugging soon

**Comment by tyler36** [comment] 2016-12-05 01:32
Steps used to produce error on Win10:
1. Check PHP version: ```PHP 7.0.8```
2. Install Laravel: ```laravel new selenium```. Move into selenium directory
3. Install pacakge: ```composer require modelizer/selenium "~1.0"```
4. Update ENV as directed but set: ```APP_URL=http://localhost:8000/```
5. Add config option to app.php
6. Start PHP server: ```php artisan serve``
7. Start Selenium server: ```php artisan selenium:start```.
8. Run tests as expected: First passes, second fails (SeleniumExampleTest::testLoginFormExample)

OK ... changed PHP version to ```5.6.18``` and restarted.
1. Check PHP version: ```PHP 5.6.18```
2. Install Laravel: ```laravel new selenium56```. Move into selenium directory
3. Install pacakge: ```composer require modelizer/selenium "~1.0"```
4. Update ENV as directed but set: ```APP_URL=http://localhost:8000/```
5. Add config option to app.php
6. Start PHP server: ```php artisan serve``
7. Start Selenium server: ```php artisan selenium:start```. 
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/openqa/grid/selenium/GridLauncher : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$000(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: org.openqa.grid.selenium.GridLauncher. Program will exit.
```

Tried again with PHP version ```5.6.28``` but hit the error again on step 7.

ENVIRONMENT:
Win10
Laravel: 5.3.26
PHPunit  5.7.2

**Comment by Modelizer** [comment] 2016-12-05 19:21
It Looks like a bug in PHP 5.6.18 https://bugs.php.net/bug.php?id=71561 which is been fixed in 5.6.19

Can you please confirm by running this command in your project directory? Selenium server should get started.

```bash
java -jar vendor/modelizer/selenium/selenium.jar -Dwebdriver.chrome.driver=vendor/bin/win-chrome.exe
```

Also, die dump this code at line 47 `vendor/modelizer/selenium/src/Console/BootSelenium.php` file and run `php artisan selenium:start` to know exactly what selenium is running under the hood.
```php
dd($command.' '.$this->getSeleniumOptions());
```

**Comment by tyler36** [comment] 2016-12-06 00:00
I get the same error on ```PHP 5.6.28```

**Comment by tyler36** [comment] 2016-12-06 00:01
I get the same error on ```PHP 5.6.28``` running
```php artisan selenium:start```

Using ```java -jar vendor/modelizer/selenium/selenium.jar -Dwebdriver.chrome.driver=vendor/bin/win-chrome.exe``` appears to start a Selenium server and the example tests work

The DD request outputs
```""java" "-jar" "I:\Lavarel\testserver\selenium56\vendor\modelizer\selenium\selenium.jar" "-Dwebdriver.chrome.driver=I:\Lavarel\testserver\selenium56\vendor/bin/win-chrome.exe" "`

**Comment by Modelizer** [comment] 2016-12-06 06:31
What is the size of your `win-chrome.exe` file?

**Comment by tyler36** [comment] 2016-12-06 06:37
Windows explorer reports the size as ```6,790kb```

**Comment by Modelizer** [comment] 2016-12-06 19:05
What if you run this command directly?
`java -jar I:\Lavarel\testserver\selenium56\vendor\modelizer\selenium\selenium.jar -Dwebdriver.chrome.driver=I:\Lavarel\testserver\selenium56\vendor\bin\win-chrome.exe`

**Comment by tyler36** [comment] 2016-12-07 00:35
Non problems running the command directly
```java -jar I:\Lavarel\testserver\selenium56\vendor\modelizer\selenium\selenium.jar -Dwebdriver.chrome.driver=I:\Lavarel\testserver\selenium56\vendor\bin\win-chrome.exe```

**Comment by Modelizer** [comment] 2016-12-18 06:25
try git bash to run commands.

Closing for now. The problem seems related to outside this package.

**Closed as completed by Modelizer** 2016-12-18 06:25 UTC
